import Nav from "@/components/frontend/Nav";
import Footer from "@/components/frontend/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function FrontPageLayout({ children }) {
  return (
    <div>
      <Nav />
      {children}
      <Footer />
    </div>
  );
}
